
project_id = "dlmbqojnhjsecajxltzj"

[auth]
site_url = "http://localhost:8080" # Define the correct local frontend site URL

[functions.verify-youtube]
verify_jwt = false

[functions.get-shared-youtube-connections]
verify_jwt = false

[functions.get-shared-fingerprints]
verify_jwt = false

[functions.get-enhanced-fingerprints]
verify_jwt = false

[functions.admin-youtube-channels-list]
verify_jwt = false

[functions.admin-youtube-channels-create]
verify_jwt = false

[functions.admin-youtube-channels-update]
verify_jwt = false

[functions.admin-youtube-channels-delete]
verify_jwt = false

[functions.admin-schedule-slots-list]
verify_jwt = false

[functions.admin-schedule-slots-create]
verify_jwt = false

[functions.admin-schedule-slots-update]
verify_jwt = false

[functions.admin-schedule-slots-delete]
verify_jwt = false

[functions.shopify-orders]
verify_jwt = false

[functions.sync-printful-orders]
verify_jwt = false


[functions.delete-user]
enabled = true
verify_jwt = true
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-user/*.html" ]

[functions.newsletter-subscribe]
enabled = true
verify_jwt = true
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/newsletter-subscribe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/newsletter-subscribe/*.html" ]

[functions.upsert-device]
enabled = true
verify_jwt = true
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upsert-device/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upsert-device/*.html" ]

[auth.external.discord]
enabled = true
client_id = "1368249016927780894"  # Replace with your Discord app's Client ID
secret = "K5MiDvCBKLOeXsKOPnGYwCBApF7Bb0lk" # Replace with your Discord app's Client Secret
redirect_uri = "http://localhost:54321/auth/v1/callback"
# Optional: specify scopes if needed, e.g., "identify email guilds"
# additional_scopes = ["identify", "email"]

[functions.order-linking]
enabled = true
verify_jwt = true # Assuming this is desired, like other functions
import_map = "./functions/order-linking/import_map.json"
entrypoint = "./functions/order-linking/index.ts"