// This file is automatically generated. Do not edit it directly. (Note: Modified for local development to use .env variables)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

// Use Vite environment variables
const supabaseUrlFromEnv = import.meta.env.VITE_PUBLIC_SUPABASE_URL;
const supabaseAnonKeyFromEnv = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrlFromEnv || !supabaseAnonKeyFromEnv) {
  throw new Error(
    'Supabase URL or Anon Key is missing from .env variables. Expected VITE_PUBLIC_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrlFromEnv, supabaseAnonKeyFromEnv);